/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorBar: typeof import('./src/components/ColorBar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    OverLay: typeof import('./src/components/OverLay.vue')['default']
    ProfileCharts: typeof import('./src/components/ProfileCharts.vue')['default']
    ScatterMap: typeof import('./src/components/ScatterMap.vue')['default']
    Tables: typeof import('./src/components/Tables.vue')['default']
    TDatePicker: typeof import('tdesign-vue-next')['DatePicker']
    TimeLine: typeof import('./src/components/TimeLine.vue')['default']
    TimeLineCharts: typeof import('./src/components/TimeLineCharts.vue')['default']
    TimeRange: typeof import('./src/components/TimeRange.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    TSpace: typeof import('tdesign-vue-next')['Space']
  }
}
